// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Issue is the predicate function for issue builders.
type Issue func(*sql.Selector)

// Todo is the predicate function for todo builders.
type Todo func(*sql.Selector)
