// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TblIssueColumns holds the columns for the "tbl_issue" table.
	TblIssueColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "url", Type: field.TypeString},
		{Name: "is_pr", Type: field.TypeBool, Default: false},
		{Name: "status", Type: field.TypeString, Nullable: true},
	}
	// TblIssueTable holds the schema information for the "tbl_issue" table.
	TblIssueTable = &schema.Table{
		Name:       "tbl_issue",
		Columns:    TblIssueColumns,
		PrimaryKey: []*schema.Column{TblIssueColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tbl_issue_todos_issue",
				Columns:    []*schema.Column{TblIssueColumns[0]},
				RefColumns: []*schema.Column{TodosColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// TodosColumns holds the columns for the "todos" table.
	TodosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// TodosTable holds the schema information for the "todos" table.
	TodosTable = &schema.Table{
		Name:       "todos",
		Columns:    TodosColumns,
		PrimaryKey: []*schema.Column{TodosColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TblIssueTable,
		TodosTable,
	}
)

func init() {
	TblIssueTable.ForeignKeys[0].RefTable = TodosTable
	TblIssueTable.Annotation = &entsql.Annotation{
		Table: "tbl_issue",
	}
}
