// Code generated by entc, DO NOT EDIT.

package entdb

import (
	"github.com/roderm/example-plugin-system/extensions/github_issue/ent/schema"
	"github.com/roderm/example-plugin-system/extensions/github_issues/ent/entdb/issue"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	issueFields := schema.Issue{}.Fields()
	_ = issueFields
	// issueDescIsPr is the schema descriptor for is_pr field.
	issueDescIsPr := issueFields[2].Descriptor()
	// issue.DefaultIsPr holds the default value on creation for the is_pr field.
	issue.DefaultIsPr = issueDescIsPr.Default.(bool)
}
