// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/roderm/example-plugin-system/app/ent/entdb"
)

// Paging Input as described:
// https://graphql.org/learn/pagination/
type Paging struct {
	After  *entdb.Cursor `json:"after"`
	First  *int          `json:"first"`
	Before *entdb.Cursor `json:"before"`
	Last   *int          `json:"last"`
}
